name: Staging
on:
  push:
    branches: [staging]
jobs:
  recruit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      # Clone repo and checkout project
      - name: Fetch source
        uses: actions/checkout@v2
      # Configure environment
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
      # Install dependencies
      - name: Install Dependencies
        run: yarn
      # Build application
      - name: Build Application
        run: yarn build
        timeout-minutes: 3
      # Configure AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION || 'ap-southeast-2' }}
      # Deploy to S3
      - name: Deploy to S3
        run: aws s3 sync ./app/dist/ s3://${{ secrets.DEV_S3_BUCKET_NAME }} --delete
        timeout-minutes: 3
